/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul-Vance Pierre Nixon Jr.
 */
public class courseSchedule extends javax.swing.JFrame {

    /**
     * Creates new form courseSchedule
     */
    public courseSchedule() {
        initComponents();
    }

    // Global variables
    Connection conn; // Connection to the MySQL database
    PreparedStatement pst; // To write queries to the database 
    ResultSet rs; // To access tables derived from queries
    DefaultTableModel dtm; // To modify the table
    String id; // The student's id;
    
    /*
    courseSchedule.java's loaded constructor loads the course(s) the students 
    enrolled in into the table.
    Pre-condition: The students enrolled in at least one course.
    Post-condition: All the courses the student enrolled in are displayed in the
    table.
    */
    courseSchedule(String id)
    {
        initComponents();
        conn = databaseConnection.Connect();
        
        try
        {
            this.id = id;
            pst = conn.prepareStatement("select c.courseDays, c.startTime, c.endTime, c.Mode, c.Name, c.courseNo, c.Instructor_Prefix, c.Instructor_lName from course c, course_enrollment_list cel "
                                     + "where c.crn = cel.crn and cel.stuID = ?");
            pst.setString(1, id);
            rs = pst.executeQuery();
            
            // Set the number of the table's rows to 0.
            ResultSetMetaData rsd = rs.getMetaData(); // To get the number of columns from the query
            dtm = (DefaultTableModel)course_info_table.getModel();
            dtm.setRowCount(0);
            
            // Load each course's info into the table.
            while (rs.next())
            {
                Vector vector = new Vector();
                
                for (int index = 1; index <= rsd.getColumnCount(); index++)
                {
					vector.add(rs.getString("courseDays"));
					vector.add(rs.getString("startTime"));
                    vector.add(rs.getString("endTime"));
					vector.add(rs.getString("mode"));
                    vector.add(rs.getString("name"));
                    vector.add(rs.getString("courseNo"));
                    //vector.add(rs.getString("description"));
                    //vector.add(rs.getString("type"));
                    vector.add(rs.getString("instructor_prefix"));
                    //vector.add(rs.getString("instructor_fName"));
                    //vector.add(rs.getString("instructor_mName"));
                    vector.add(rs.getString("instructor_lName"));
                    //vector.add(rs.getString("instructor_suffix"));
                    //vector.add(rs.getString("numStudents"));
                    //vector.add(rs.getString("maxStudents"));
                    //vector.add(rs.getString("credits"));
                    //vector.add(rs.getString("location"));
                    //vector.add(rs.getString("classroomNo"));
                    //vector.add(rs.getString("crn"));
                }
                
                dtm.addRow(vector); // Adds a course's info as one of the table's rows
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(courseSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        course_info_scroll_table = new javax.swing.JScrollPane();
        course_info_table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        backButton = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        course_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                //"Name", "courseNo", "Description", "College", "Department", "Type", "Mode", "Instructor_Prefix", "Instructor_fName", "Instructor_mName", "Instructor_lName", "Instructor_Suffix", "numStudents", "maxStudents", "Credits", "startTime", "endTime", "Location", "classroomNo", "courseDays", "CRN"
				"courseDays", "startTime", "endTime", "mode", "name", "courseNo", "instructor_prefix", "instructor_lName"
            }
        ) {
            Class[] types = new Class [] {
                //java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
				java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        course_info_scroll_table.setViewportView(course_info_table);

        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(backButton);

        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(course_info_scroll_table, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(course_info_scroll_table, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // Display studentHome.java.
        this.hide();
        new studentHome(id).setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // Display Login.java.
        this.hide();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courseSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu backButton;
    private javax.swing.JScrollPane course_info_scroll_table;
    private javax.swing.JTable course_info_table;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logoutButton;
    // End of variables declaration//GEN-END:variables
}
