/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul-Vance Pierre Nixon Jr.
 */
public class modifyDegreeInfo extends javax.swing.JFrame {

    /**
     * Creates new form modifyDegreeInfo
     */
    public modifyDegreeInfo() {
        initComponents();
        conn = databaseConnection.Connect();
        degreeLoad();
        
        try
        {
            // Load each college's name.
            pst = conn.prepareStatement("select name from college");
            rs = pst.executeQuery();
            
            // Load all the colleges' names into the combo box.
            while (rs.next())
                college_combo_box.addItem(rs.getString("name"));           
        }
        catch (SQLException ex)
        {
            Logger.getLogger(modifyDepartmentInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Global variables
    Connection conn; // Connection to the MySQL database
    PreparedStatement pst; // To write queries to the database 
    ResultSet rs; // To access tables derived from queries
    DefaultTableModel dtm; // To modify the table
    
    /*
    degreeLoad() is a fetch function which retrieves every degree's info from the
    MySQL database and renders them in the table.
    Pre-condition: There's at least one degree entry in the database.
    Post-condition: The degrees' info is rendered in the table.
    */
    private void degreeLoad()
    {
        try
        {
            // Load each degree's info.
            pst = conn.prepareStatement("select * from degree");
            rs = pst.executeQuery();
            
            // Set the number of the table's rows to 0.
            ResultSetMetaData rsd = rs.getMetaData(); // To get the number of columns from the query
            dtm = (DefaultTableModel)degree_info_table.getModel();
            dtm.setRowCount(0);
            
            // Load each degree's info into the table.
            while (rs.next())
            {
                Vector vector = new Vector();
                
                for (int index = 1; index <= rsd.getColumnCount(); index++)
                {
                    vector.add(rs.getString("name"));
                    vector.add(rs.getString("type"));
                    vector.add(rs.getString("college"));
                    vector.add(rs.getString("department"));
                }
                
                dtm.addRow(vector); // Adds a degree's info as one of the table's rows
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(modifyDegreeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degree_info_form = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_text_field = new javax.swing.JTextField();
        type_label = new javax.swing.JLabel();
        type_combo_box = new javax.swing.JComboBox<>();
        college_label = new javax.swing.JLabel();
        college_combo_box = new javax.swing.JComboBox<>();
        dept_label = new javax.swing.JLabel();
        dept_combo_box = new javax.swing.JComboBox<>();
        degree_info_scroll_pane = new javax.swing.JScrollPane();
        degree_info_table = new javax.swing.JTable();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        modifyDegreeInfo_MenuBar = new javax.swing.JMenuBar();
        backButton = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        degree_info_form.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        name_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name_label.setText("Name:");

        type_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        type_label.setText("Type:");

        type_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.S.", "B.S.", "M.S.", "Ph.D." }));
        type_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        college_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        college_label.setText("College:");

        college_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dept_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dept_label.setText("Department:");

        dept_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dept_combo_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dept_combo_boxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout degree_info_formLayout = new javax.swing.GroupLayout(degree_info_form);
        degree_info_form.setLayout(degree_info_formLayout);
        degree_info_formLayout.setHorizontalGroup(
            degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(degree_info_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(degree_info_formLayout.createSequentialGroup()
                        .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_label)
                            .addComponent(type_label))
                        .addGap(18, 18, 18)
                        .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(degree_info_formLayout.createSequentialGroup()
                        .addComponent(college_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(college_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(degree_info_formLayout.createSequentialGroup()
                        .addComponent(dept_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dept_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        degree_info_formLayout.setVerticalGroup(
            degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(degree_info_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_label)
                    .addComponent(type_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(college_label)
                    .addComponent(college_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(degree_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept_label)
                    .addComponent(dept_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        degree_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "College", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        degree_info_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        degree_info_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                degree_info_tableMouseClicked(evt);
            }
        });
        degree_info_scroll_pane.setViewportView(degree_info_table);

        insertButton.setText("Insert");
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonMouseClicked(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        modifyDegreeInfo_MenuBar.add(backButton);

        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        modifyDegreeInfo_MenuBar.add(logoutButton);

        setJMenuBar(modifyDegreeInfo_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))
                    .addComponent(degree_info_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(degree_info_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(degree_info_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertButton)
                            .addComponent(updateButton)
                            .addComponent(deleteButton)
                            .addComponent(clearButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(degree_info_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // Return to adminHome.java.
        this.hide();
        new adminHome().setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // Return to Login.java.
        this.hide(); 
        new Login().setVisible(true); // Displays Login.java
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void degree_info_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_degree_info_tableMouseClicked
        // Get the clicked row.
        dtm = (DefaultTableModel)degree_info_table.getModel();
        int selectedIndex = degree_info_table.getSelectedRow();
        
        // Set every field in the form to its respective table value.
        name_text_field.setText(dtm.getValueAt(selectedIndex, 0).toString());
        type_combo_box.setSelectedItem(dtm.getValueAt(selectedIndex, 1));
        college_combo_box.setSelectedItem(dtm.getValueAt(selectedIndex, 2));
        dept_combo_box.setSelectedItem(dtm.getValueAt(selectedIndex, 3));
        
        // Disable the insert button.
        insertButton.setEnabled(false);
    }//GEN-LAST:event_degree_info_tableMouseClicked

    private void insertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonMouseClicked
        /*
        Check if the admin filled all the text fields. If not, display a pop-up 
        telling them to fill the specified text field. If so, insert the new
        degree's info into the database.
        */
        if (name_text_field.getText().isEmpty() || name_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Name' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else
        {
            try
            {
                // Insert the values into the database.
                pst = conn.prepareStatement("insert into degree values(?,?,?,?)");
                pst.setString(1, name_text_field.getText());
                pst.setString(2, type_combo_box.getSelectedItem().toString());
                pst.setString(3, college_combo_box.getSelectedItem().toString());
                pst.setString(4, dept_combo_box.getSelectedItem().toString());
                pst.executeUpdate();
            
                /* Confirm to the admin that a new degree's info has been added
                   to the database, clear the form, 
                   and reload all the remaining degrees' info.
                */
                JOptionPane.showMessageDialog(this, "New degree added.");
                name_text_field.setText("");
                type_combo_box.setSelectedIndex(0);
                college_combo_box.setSelectedIndex(0);
                dept_combo_box.setSelectedIndex(0);
                degreeLoad();
            }
            catch (SQLException ex)
            {
                Logger.getLogger(modifyDegreeInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_insertButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        /*
        Check if the admin filled all the text fields. If not, display a pop-up 
        telling them to fill the specified text field. If so, update the selected
        degree's info.
        */
        if (name_text_field.getText().isEmpty() || name_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Name' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else
        {
            try
            {
                // Get the clicked row.
                dtm = (DefaultTableModel)degree_info_table.getModel();
                int selectedIndex = degree_info_table.getSelectedRow();
            
                // Update each of the selected degree's info to its respective field's value.
                pst = conn.prepareStatement("update degree set name = ?, type = ?, "
                                          + "college = ?, department = ? where name = ? "
                                          + "and type = ?");
                pst.setString(1, name_text_field.getText());
                pst.setString(2, type_combo_box.getSelectedItem().toString());
                pst.setString(3, college_combo_box.getSelectedItem().toString());
                pst.setString(4, dept_combo_box.getSelectedItem().toString());
                pst.setString(5, dtm.getValueAt(selectedIndex, 0).toString());
                pst.setString(6, dtm.getValueAt(selectedIndex, 1).toString());
                pst.executeUpdate();
            
                /* Confirm to the admin that the selected degree's info has been updated,
                   clear the form, and reload each degree's info.
                */
                JOptionPane.showMessageDialog(this, "Degree's info is updated.");
                insertButton.setEnabled(true); // Enables the Insert button
                name_text_field.setText("");
                type_combo_box.setSelectedIndex(0);
                college_combo_box.setSelectedIndex(0);
                dept_combo_box.setSelectedIndex(0);
                degreeLoad();
            }
            catch (SQLException ex)
            {
                Logger.getLogger(modifyDegreeInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        try
        {
            // Get the clicked row.
            dtm = (DefaultTableModel)degree_info_table.getModel();
            int selectedIndex = degree_info_table.getSelectedRow();
            
            // Delete the selected degree's info from both the database and the table.
            pst = conn.prepareStatement("delete from degree where name = ? and type = ?");
            pst.setString(1, dtm.getValueAt(selectedIndex, 0).toString());
            pst.setString(2, dtm.getValueAt(selectedIndex, 1).toString());
            pst.executeUpdate();
            
            /* Confirm to the admin that the selected degree's info has been deleted,
               clear the form, and reload the remaining degrees' info.
            */
            JOptionPane.showMessageDialog(this, "Degree's info is deleted.");
            insertButton.setEnabled(true); // Enables the Insert button
            insertButton.setEnabled(true); // Enables the Insert button
            name_text_field.setText("");
            type_combo_box.setSelectedIndex(0);
            college_combo_box.setSelectedIndex(0);
            dept_combo_box.setSelectedIndex(0);
            degreeLoad();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(modifyDegreeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // Clear every field.
        name_text_field.setText("");
        type_combo_box.setSelectedIndex(0);
        college_combo_box.setSelectedIndex(0);
        dept_combo_box.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonMouseClicked

    private void dept_combo_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dept_combo_boxMouseClicked
        try
        {
            /*
            Load each deprtment's name which corresponds to the college that the admin
            chose.
            */
            pst = conn.prepareStatement("select name from department where college = ?");
            pst.setString(1, college_combo_box.getSelectedItem().toString());
            rs = pst.executeQuery();

            // Load all the departments' names into the combo box.
            dept_combo_box.removeAllItems();
            while (rs.next())
                dept_combo_box.addItem(rs.getString("name"));            
        }
        catch (SQLException ex)
        {
            Logger.getLogger(registerStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dept_combo_boxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifyDegreeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifyDegreeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifyDegreeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifyDegreeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifyDegreeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> college_combo_box;
    private javax.swing.JLabel college_label;
    private javax.swing.JPanel degree_info_form;
    private javax.swing.JScrollPane degree_info_scroll_pane;
    private javax.swing.JTable degree_info_table;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> dept_combo_box;
    private javax.swing.JLabel dept_label;
    private javax.swing.JButton insertButton;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JMenuBar modifyDegreeInfo_MenuBar;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text_field;
    private javax.swing.JComboBox<String> type_combo_box;
    private javax.swing.JLabel type_label;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
