/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul-Vance Pierre Nixon Jr.
 */
public class modifyCollegeInfo extends javax.swing.JFrame {

    /**
     * Creates new form modifyCollegeInfo
     */
    public modifyCollegeInfo() {
        initComponents();
        conn = databaseConnection.Connect();
        collegeLoad();
    }

    
    // Global variables
    Connection conn; // Connection to the MySQL database
    PreparedStatement pst; // To write queries to the database 
    ResultSet rs; // To access tables derived from queries
    DefaultTableModel dtm; // To modify the table
    
    /*
    collegeLoad() is a fetch function which retrieves every college's info from the
    MySQL database and renders them in the table.
    Pre-condition: There's at least one college entry in the database.
    Post-condition: The colleges' info is rendered in the table.
    */
    private void collegeLoad()
    {
        try
        {
            // Load each college's info.
            pst = conn.prepareStatement("select * from college");
            rs = pst.executeQuery();
            
            // Set the number of the table's rows to 0.
            ResultSetMetaData rsd = rs.getMetaData(); // To get the number of columns from the query
            dtm = (DefaultTableModel)college_info_table.getModel();
            dtm.setRowCount(0);
            
            // Load each college's info into the table.
            while (rs.next())
            {
                Vector vector = new Vector();
                
                for (int index = 1; index <= rsd.getColumnCount(); index++)
                {
                    vector.add(rs.getString("name"));
                    vector.add(rs.getString("address"));
                    vector.add(rs.getString("email"));
                    vector.add(rs.getString("officeNo"));
                    vector.add(rs.getString("deanPrefix"));
                    vector.add(rs.getString("dean_fName"));
                    vector.add(rs.getString("dean_mName"));
                    vector.add(rs.getString("dean_lName"));
                    vector.add(rs.getString("deanSuffix"));
                    vector.add(rs.getString("assocDean_prefix"));
                    vector.add(rs.getString("assocDean_fName"));
                    vector.add(rs.getString("assocDean_mName"));
                    vector.add(rs.getString("assocDean_lName"));
                    vector.add(rs.getString("assocDean_suffix"));
                    vector.add(rs.getString("asstDean_prefix"));
                    vector.add(rs.getString("asstDean_fName"));
                    vector.add(rs.getString("asstDean_mName"));
                    vector.add(rs.getString("asstDean_lName"));
                    vector.add(rs.getString("asstDean_suffix"));
                    vector.add(rs.getString("telNo"));
                    vector.add(rs.getString("faxNo"));
                    vector.add(rs.getString("advisingNo"));
                    vector.add(rs.getString("advisingEmail"));
                }
                
                dtm.addRow(vector); // Adds a college's info as one of the table's rows
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(modifyCollegeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        college_info_form = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_text_field = new javax.swing.JTextField();
        address_label = new javax.swing.JLabel();
        address_text_field = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        officeNo_label = new javax.swing.JLabel();
        officeNo_text_field = new javax.swing.JFormattedTextField();
        telNo_label = new javax.swing.JLabel();
        telNo_text_field = new javax.swing.JFormattedTextField();
        faxNo_label = new javax.swing.JLabel();
        faxNo_text_field = new javax.swing.JFormattedTextField();
        advisingNo_label = new javax.swing.JLabel();
        advisingNo_text_field = new javax.swing.JFormattedTextField();
        advisingEmail_label = new javax.swing.JLabel();
        email_text_field = new javax.swing.JTextField();
        advisingEmail_text_field = new javax.swing.JTextField();
        college_info_scroll_pane = new javax.swing.JScrollPane();
        college_info_table = new javax.swing.JTable();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        modifyCollegeInfo_MenuBar = new javax.swing.JMenuBar();
        backButton = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        college_info_form.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        name_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name_label.setText("Name:");

        address_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        address_label.setText("Address:");

        email_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email_label.setText("Email:");

        officeNo_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        officeNo_label.setText("Office Number:");

        try {
            officeNo_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U-###*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        telNo_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telNo_label.setText("Phone:");

        try {
            telNo_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("555-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        faxNo_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        faxNo_label.setText("Fax:");

        try {
            faxNo_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("555-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        advisingNo_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        advisingNo_label.setText("Advising Office Number:");

        try {
            advisingNo_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U-###*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        advisingEmail_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        advisingEmail_label.setText("Advising Office Email:");

        javax.swing.GroupLayout college_info_formLayout = new javax.swing.GroupLayout(college_info_form);
        college_info_form.setLayout(college_info_formLayout);
        college_info_formLayout.setHorizontalGroup(
            college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(college_info_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(college_info_formLayout.createSequentialGroup()
                        .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(college_info_formLayout.createSequentialGroup()
                                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address_label)
                                    .addComponent(email_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(address_text_field, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(email_text_field)))
                            .addGroup(college_info_formLayout.createSequentialGroup()
                                .addComponent(name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(college_info_formLayout.createSequentialGroup()
                                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(officeNo_label)
                                    .addComponent(telNo_label)
                                    .addComponent(faxNo_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(officeNo_text_field)
                                    .addComponent(telNo_text_field)
                                    .addComponent(faxNo_text_field))))
                        .addGap(72, 72, 72))
                    .addGroup(college_info_formLayout.createSequentialGroup()
                        .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advisingNo_label)
                            .addComponent(advisingEmail_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(college_info_formLayout.createSequentialGroup()
                                .addComponent(advisingNo_text_field)
                                .addGap(72, 72, 72))
                            .addGroup(college_info_formLayout.createSequentialGroup()
                                .addComponent(advisingEmail_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        college_info_formLayout.setVerticalGroup(
            college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(college_info_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_label)
                    .addComponent(address_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_label)
                    .addComponent(email_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeNo_label)
                    .addComponent(officeNo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNo_label)
                    .addComponent(telNo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faxNo_label)
                    .addComponent(faxNo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advisingNo_label)
                    .addComponent(advisingNo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(college_info_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advisingEmail_label)
                    .addComponent(advisingEmail_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        college_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Email", "OfficeNo", "DeanPrefix", "Dean_fName", "Dean_mName", "Dean_lName", "DeanSuffix", "assocDean_Prefix", "assocDean_fName", "assocDean_mName", "assocDean_lName", "assocDean_Suffix", "asstDean_Prefix", "asstDean_fName", "asstDean_mName", "asstDean_lName", "asstDean_Suffix", "telNo", "faxNo", "advisingNo", "advisingEmail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        college_info_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        college_info_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                college_info_tableMouseClicked(evt);
            }
        });
        college_info_scroll_pane.setViewportView(college_info_table);

        insertButton.setText("Insert");
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonMouseClicked(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        modifyCollegeInfo_MenuBar.add(backButton);

        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        modifyCollegeInfo_MenuBar.add(logoutButton);

        setJMenuBar(modifyCollegeInfo_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(college_info_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(college_info_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(college_info_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(college_info_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(clearButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void college_info_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_college_info_tableMouseClicked
        // Get the clicked row.
        dtm = (DefaultTableModel)college_info_table.getModel();
        int selectedIndex = college_info_table.getSelectedRow();
        
        // Set every field in the form to its respective table value.
        name_text_field.setText(dtm.getValueAt(selectedIndex, 0).toString());
        address_text_field.setText(dtm.getValueAt(selectedIndex, 1).toString());
        email_text_field.setText(dtm.getValueAt(selectedIndex, 2).toString());
        officeNo_text_field.setText(dtm.getValueAt(selectedIndex, 3).toString());
        telNo_text_field.setText(dtm.getValueAt(selectedIndex, 19).toString());
        faxNo_text_field.setText(dtm.getValueAt(selectedIndex, 20).toString());
        advisingNo_text_field.setText(dtm.getValueAt(selectedIndex, 21).toString());
        advisingEmail_text_field.setText(dtm.getValueAt(selectedIndex, 22).toString());
        
        // Disable the Insert button.
        insertButton.setEnabled(false);
    }//GEN-LAST:event_college_info_tableMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // Return to adminHome.java.
        this.hide();
        new adminHome().setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // Return to Login.java.
        this.hide(); 
        new Login().setVisible(true); // Displays Login.java
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void insertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonMouseClicked
        /*
        Check if the admin filled all the text fields. If not, display a pop-up 
        telling them to fill the specified text field. If so, insert the new
        college's info into the database.
        */
        if (name_text_field.getText().isEmpty() || name_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Name' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else if (address_text_field.getText().isEmpty() || address_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Email' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email_text_field.getText())) || email_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Email' text field is either "
                                         + "invalid or exceeds 30 characters.");
        }
        else if (telNo_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Phone' text field is empty.");
        else if (faxNo_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Fax' text field is empty.");
        else if (advisingNo_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Advising office number' text field is empty.");
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", advisingEmail_text_field.getText())) || advisingEmail_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Advising Email' text field is either "
                                         + "invalid or exceeds 30 characters.");
        }
        else
        {
            try
            {
                // Insert the values into the database.
                pst = conn.prepareStatement("insert into college(name, address, email, "
                                          + "officeNo, telNo, faxNo, advisingNo, "
                                          + "advisingEmail) values(?,?,?,?,?,?,?,?)");
                pst.setString(1, name_text_field.getText());
                pst.setString(2, address_text_field.getText());
                pst.setString(3, email_text_field.getText());
                pst.setString(4, officeNo_text_field.getText());
                pst.setString(5, telNo_text_field.getText());
                pst.setString(6, faxNo_text_field.getText());
                pst.setString(7, advisingNo_text_field.getText());
                pst.setString(8, advisingEmail_text_field.getText());
                pst.executeUpdate();
            
                /*
                Confirm to the admin that a new college has been added to the database
                and clear the form.
                */
                JOptionPane.showMessageDialog(this, "New college added.");
                name_text_field.setText("");
                address_text_field.setText("");
                email_text_field.setText("");
                officeNo_text_field.setText("");
                telNo_text_field.setText("");
                faxNo_text_field.setText("");
                advisingNo_text_field.setText("");
                advisingEmail_text_field.setText("");
                collegeLoad();
            }
            catch (SQLException ex)
            {
                Logger.getLogger(modifyCollegeInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_insertButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        /*
        Check if the admin filled all the text fields. If not, display a pop-up 
        telling them to fill the specified text field. If so, update the selected
        college's info.
        */
        if (name_text_field.getText().isEmpty() || name_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Name' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else if (address_text_field.getText().isEmpty() || address_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Email' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email_text_field.getText())) || email_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Email' text field is either "
                                         + "invalid or exceeds 30 characters.");
        }
        else if (telNo_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Phone' text field is empty.");
        else if (faxNo_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Fax' text field is empty.");
        else if (advisingNo_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Advising office number' text field is empty.");
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email_text_field.getText())) || email_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Advising Email' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else
        {
            try
            {
                // Get the selected row.
                dtm = (DefaultTableModel)college_info_table.getModel();
                int selectedIndex = college_info_table.getSelectedRow();
            
                // Update each of the selected college's info to its respective field's value.
                pst = conn.prepareStatement("update college set name = ?, address = ?, "
                                          + "email = ?, officeNo = ?, telNo = ?, faxNo = ?, "
                                          + "advisingNo = ?, advisingEmail = ? "
                                          + "where name = ?");
                pst.setString(1, name_text_field.getText());
                pst.setString(2, address_text_field.getText());
                pst.setString(3, email_text_field.getText());
                pst.setString(4, officeNo_text_field.getText());
                pst.setString(5, telNo_text_field.getText());
                pst.setString(6, faxNo_text_field.getText());
                pst.setString(7, advisingNo_text_field.getText());
                pst.setString(8, advisingEmail_text_field.getText());
                pst.setString(9, dtm.getValueAt(selectedIndex, 0).toString());
                pst.executeUpdate();
             
                /* Confirm to the admin that the selected college's info has been updated,
                   clear the form, and reload all the remaining colleges' info.
                */
                JOptionPane.showMessageDialog(this, "College's info is updated.");
                insertButton.setEnabled(true); // Enables the Insert button
                name_text_field.setText("");
                address_text_field.setText("");
                email_text_field.setText("");
                officeNo_text_field.setText("");
                telNo_text_field.setText("");
                faxNo_text_field.setText("");
                advisingNo_text_field.setText("");
                advisingEmail_text_field.setText("");
                collegeLoad();
            }
            catch (SQLException ex)
            {
                Logger.getLogger(modifyCollegeInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        try
        {
            // Get the selected row.
            dtm = (DefaultTableModel)college_info_table.getModel();
            int selectedIndex = college_info_table.getSelectedRow();
            
            // Delete the selected college's info from both the database and the table.
            pst = conn.prepareStatement("delete from college where name = ?");
            pst.setString(1, dtm.getValueAt(selectedIndex, 0).toString());
            pst.executeUpdate();
            
            /* Confirm to the admin that the selected college's info has been deleted,
               clear the form, and reload the remaining colleges' info.
            */
            JOptionPane.showMessageDialog(this, "College's info is deleted.");
            insertButton.setEnabled(true); // Enables the Insert button
            name_text_field.setText("");
            address_text_field.setText("");
            email_text_field.setText("");
            officeNo_text_field.setText("");
            telNo_text_field.setText("");
            faxNo_text_field.setText("");
            advisingNo_text_field.setText("");
            advisingEmail_text_field.setText("");
            collegeLoad();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(modifyCollegeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // Clear all the text fields.
        insertButton.setEnabled(true); // Enables the Insert button
        name_text_field.setText("");
        address_text_field.setText("");
        email_text_field.setText("");
        officeNo_text_field.setText("");
        telNo_text_field.setText("");
        faxNo_text_field.setText("");
        advisingNo_text_field.setText("");
        advisingEmail_text_field.setText("");
    }//GEN-LAST:event_clearButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifyCollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifyCollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifyCollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifyCollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifyCollegeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_label;
    private javax.swing.JTextField address_text_field;
    private javax.swing.JLabel advisingEmail_label;
    private javax.swing.JTextField advisingEmail_text_field;
    private javax.swing.JLabel advisingNo_label;
    private javax.swing.JFormattedTextField advisingNo_text_field;
    private javax.swing.JMenu backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel college_info_form;
    private javax.swing.JScrollPane college_info_scroll_pane;
    private javax.swing.JTable college_info_table;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_text_field;
    private javax.swing.JLabel faxNo_label;
    private javax.swing.JFormattedTextField faxNo_text_field;
    private javax.swing.JButton insertButton;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JMenuBar modifyCollegeInfo_MenuBar;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text_field;
    private javax.swing.JLabel officeNo_label;
    private javax.swing.JFormattedTextField officeNo_text_field;
    private javax.swing.JLabel telNo_label;
    private javax.swing.JFormattedTextField telNo_text_field;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
