/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul-Vance Pierre Nixon Jr.
 */
public class registerAdmin extends javax.swing.JFrame {

    /**
     * Creates new form registerAdmin
     */
    public registerAdmin() {
        initComponents();
        conn = databaseConnection.Connect();
    }

    // Global variables
    Connection conn; // Connection to the MySQL database
    PreparedStatement pst; // To write queries to the database 
    ResultSet rs; // To access tables derived from queries
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_registration_label = new javax.swing.JLabel();
        prefix_label = new javax.swing.JLabel();
        prefix_combo_box = new javax.swing.JComboBox<>();
        fName_label = new javax.swing.JLabel();
        fName_text_field = new javax.swing.JTextField();
        mName_label = new javax.swing.JLabel();
        mName_text_field = new javax.swing.JTextField();
        lName_label = new javax.swing.JLabel();
        lName_text_field = new javax.swing.JTextField();
        suffix_label = new javax.swing.JLabel();
        suffix_combo_box = new javax.swing.JComboBox<>();
        dob_label = new javax.swing.JLabel();
        dob_text_field = new javax.swing.JFormattedTextField();
        gender_label = new javax.swing.JLabel();
        gender_combo_box = new javax.swing.JComboBox<>();
        ethnicity_label = new javax.swing.JLabel();
        ethnicity_combo_box = new javax.swing.JComboBox<>();
        email_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_text_field = new javax.swing.JPasswordField();
        phone_label = new javax.swing.JLabel();
        phone_text_field = new javax.swing.JFormattedTextField();
        backButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        email_text_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin_registration_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        admin_registration_label.setForeground(java.awt.Color.black);
        admin_registration_label.setText("Admin Registration");

        prefix_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prefix_label.setText("Prefix:");

        prefix_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Dr.", "Miss", "Mr.", "Mrs.", "Ms.", "Professor" }));
        prefix_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        fName_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fName_label.setText("First name:");

        mName_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mName_label.setText("Middle name:");

        lName_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lName_label.setText("Last name:");

        suffix_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        suffix_label.setText("Suffix:");

        suffix_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Esq.", "I", "II", "III", "IV", "V", "VI", "VII", "M.D.", "Ph.D.", "Jr.", "Sr." }));
        suffix_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dob_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dob_label.setText("DOB:");

        dob_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y/M/d"))));

        gender_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gender_label.setText("Gender:");

        gender_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        gender_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ethnicity_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ethnicity_label.setText("Ethnicity:");

        ethnicity_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hispanic or Latino", "American Indian or Alaska Native", "Asian", "Black or African American", "Native Hawaiian or Other Pacific Islander", "White" }));
        ethnicity_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        email_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email_label.setText("Email:");

        password_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        password_label.setText("Password:");

        phone_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phone_label.setText("Phone:");

        try {
            phone_text_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("555-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))
                    .addComponent(dob_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prefix_label)
                        .addGap(18, 18, 18)
                        .addComponent(prefix_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(admin_registration_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(mName_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mName_text_field))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(fName_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fName_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lName_label)
                                            .addComponent(suffix_label))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(gender_label)
                                        .addGap(38, 38, 38)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(ethnicity_label)
                                    .addGap(27, 27, 27)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ethnicity_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gender_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(suffix_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lName_text_field)
                                .addComponent(dob_text_field))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(email_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(phone_label)
                                .addGap(42, 42, 42)
                                .addComponent(phone_text_field))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email_label)
                                    .addComponent(password_label))
                                .addGap(22, 22, 22)
                                .addComponent(password_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(admin_registration_label)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefix_label)
                    .addComponent(prefix_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fName_label)
                    .addComponent(fName_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mName_label)
                    .addComponent(mName_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName_label)
                    .addComponent(lName_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suffix_label)
                    .addComponent(suffix_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob_label)
                    .addComponent(dob_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_label)
                    .addComponent(gender_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ethnicity_label)
                    .addComponent(ethnicity_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_label)
                    .addComponent(email_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label)
                    .addComponent(password_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_label)
                    .addComponent(phone_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(enterButton)
                    .addComponent(clearButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // Display Login.java.
        this.hide();
        new Login().setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void enterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterButtonMouseClicked
        /*
        Check if the admin filled all the text fields. If not, display a pop-up 
        telling them to fill the specified text field. If so, insert the new
        admin's info into the database.
        */
        if (fName_text_field.getText().isEmpty() || fName_text_field.getText().length() > 20)
        {
            JOptionPane.showMessageDialog(this, "The 'First name' text field is either "
                                         + "empty or exceeds 20 characters.");
        }
        else if (mName_text_field.getText().isEmpty() || mName_text_field.getText().length() > 20)
        {
            JOptionPane.showMessageDialog(this, "The 'Middle name' text field is either "
                                         + "empty or exceeds 20 characters.");
        }
        else if (lName_text_field.getText().isEmpty() || lName_text_field.getText().length() > 20)
        {
            JOptionPane.showMessageDialog(this, "The 'Last name' text field is either "
                                         + "empty or exceeds 20 characters.");
        }
        else if (dob_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'DOB' text field is empty.");
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email_text_field.getText())) || email_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Email' text field is either "
                                         + "invalid or exceeds 30 characters.");
        }
        else if (password_text_field.getText().isEmpty() || password_text_field.getText().length() > 30)
        {
            JOptionPane.showMessageDialog(this, "The 'Password' text field is either "
                                         + "empty or exceeds 30 characters.");
        }
        else if (phone_text_field.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "The 'Phone' text field is empty.");
        else
        {
            try
            {
                String username = email_text_field.getText().substring(0, 
                                    email_text_field.getText().indexOf('@'));
                String uniEmail = username + "@mascot.uni.edu";
            
                // Insert the values into the database.
                pst = conn.prepareStatement("insert into admin(prefix, fName, mName, lName, "
                                          + "suffix, DOB, gender, ethnicity, email, uniEmail, "
                                          + "password, username, telNo) "
                                          + "values(?,?,?,?,?,?,?,?,?,?,"
                                          + "?,?,?)");
                pst.setString(1, prefix_combo_box.getSelectedItem().toString());
                pst.setString(2, fName_text_field.getText());
                pst.setString(3, mName_text_field.getText());
                pst.setString(4, lName_text_field.getText());
                pst.setString(5, suffix_combo_box.getSelectedItem().toString());
                pst.setString(6, dob_text_field.getText());
                pst.setString(7, gender_combo_box.getSelectedItem().toString());
                pst.setString(8, ethnicity_combo_box.getSelectedItem().toString());
                pst.setString(9, email_text_field.getText());
                pst.setString(10, uniEmail);
                pst.setString(11, password_text_field.getText());
                pst.setString(12, username);
                pst.setString(13, phone_text_field.getText());
                pst.executeUpdate();
            
                /* Confirm to the admin that their info is in the datbase and
                   clear the form.
                */
                JOptionPane.showMessageDialog(this, "You're a new admin!");
                fName_text_field.setText("");
                mName_text_field.setText("");
                lName_text_field.setText("");
                dob_text_field.setText("");
                email_text_field.setText("");
                password_text_field.setText("");
                phone_text_field.setText("");
            }
            catch (SQLException ex)
            {
                Logger.getLogger(registerAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enterButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // Clear all the text fields.
        fName_text_field.setText("");
        mName_text_field.setText("");
        lName_text_field.setText("");
        dob_text_field.setText("");
        email_text_field.setText("");
        password_text_field.setText("");
        phone_text_field.setText("");
    }//GEN-LAST:event_clearButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_registration_label;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dob_label;
    private javax.swing.JFormattedTextField dob_text_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_text_field;
    private javax.swing.JButton enterButton;
    private javax.swing.JComboBox<String> ethnicity_combo_box;
    private javax.swing.JLabel ethnicity_label;
    private javax.swing.JLabel fName_label;
    private javax.swing.JTextField fName_text_field;
    private javax.swing.JComboBox<String> gender_combo_box;
    private javax.swing.JLabel gender_label;
    private javax.swing.JLabel lName_label;
    private javax.swing.JTextField lName_text_field;
    private javax.swing.JLabel mName_label;
    private javax.swing.JTextField mName_text_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_text_field;
    private javax.swing.JLabel phone_label;
    private javax.swing.JFormattedTextField phone_text_field;
    private javax.swing.JComboBox<String> prefix_combo_box;
    private javax.swing.JLabel prefix_label;
    private javax.swing.JComboBox<String> suffix_combo_box;
    private javax.swing.JLabel suffix_label;
    // End of variables declaration//GEN-END:variables
}
