/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

/**
 *
 * @author Paul-Vance Pierre Nixon Jr.
 */
public class studentHome extends javax.swing.JFrame {

    /**
     * Creates new form studentHome
     */
    public studentHome() {
        initComponents();
    }

    // Global variables
    String id; // The student's id
    
    studentHome(String id) // Loaded constructor
    {
        initComponents();
        this.id = id;
        student_id_label.setText("ID: " + id);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personal_info_button = new javax.swing.JButton();
        course_registration_button = new javax.swing.JButton();
        student_home_label = new javax.swing.JLabel();
        student_id_label = new javax.swing.JLabel();
        course_schedule_button = new javax.swing.JButton();
        studentHome_MenuBar = new javax.swing.JMenuBar();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personal_info_button.setText("Personal Info");
        personal_info_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personal_info_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personal_info_buttonMouseClicked(evt);
            }
        });

        course_registration_button.setText("Course Registration");
        course_registration_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        course_registration_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                course_registration_buttonMouseClicked(evt);
            }
        });

        student_home_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        student_home_label.setForeground(java.awt.Color.black);
        student_home_label.setText("Student Home");

        student_id_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        student_id_label.setText("jLabel1");

        course_schedule_button.setText("Course Schedule");
        course_schedule_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        course_schedule_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                course_schedule_buttonMouseClicked(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        studentHome_MenuBar.add(logoutButton);

        setJMenuBar(studentHome_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(student_id_label)
                .addGap(105, 105, 105)
                .addComponent(student_home_label)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personal_info_button)
                .addGap(18, 18, 18)
                .addComponent(course_registration_button)
                .addGap(18, 18, 18)
                .addComponent(course_schedule_button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(student_home_label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(student_id_label)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personal_info_button)
                    .addComponent(course_registration_button)
                    .addComponent(course_schedule_button))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personal_info_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personal_info_buttonMouseClicked
        // Display studentPersonalInfo.java.
        this.hide();
        new studentPersonalInfo(id).setVisible(true);
    }//GEN-LAST:event_personal_info_buttonMouseClicked

    private void course_registration_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_course_registration_buttonMouseClicked
        // Display courseRegistration.java.
        this.hide();
        new courseRegistration(id).setVisible(true);
    }//GEN-LAST:event_course_registration_buttonMouseClicked

    private void course_schedule_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_course_schedule_buttonMouseClicked
        // Display courseSchedule.java.
        this.hide();
        new courseSchedule(id).setVisible(true);
    }//GEN-LAST:event_course_schedule_buttonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        this.hide();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton course_registration_button;
    private javax.swing.JButton course_schedule_button;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JButton personal_info_button;
    private javax.swing.JMenuBar studentHome_MenuBar;
    private javax.swing.JLabel student_home_label;
    private javax.swing.JLabel student_id_label;
    // End of variables declaration//GEN-END:variables
}
