/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul-Vance Pierre Nixon Jr.
 */
public class viewStudents extends javax.swing.JFrame {

    /**
     * Creates new form viewStudents
     */
    public viewStudents() {
        initComponents();
    }

    // Global variables
    Connection conn; // Connection to the MySQL database
    PreparedStatement pst; // To write queries to the database 
    ResultSet rs; // To access tables derived from queries
    DefaultTableModel dtm; // To modify the info table
    String id; // The staff member's ID
    
    viewStudents(String id) // Loaded constructor
    {
        initComponents();
        conn = databaseConnection.Connect();
        this.id = id;
        studentLoad();
    }
    
    /*
    studentLoad() is a fetch function which retrieves every student's info from the
    MySQL database and renders them in the table.
    Pre-condition: There's at least one student entry in the database.
    Post-condition: The students' info is rendered in the table.
    */
    private void studentLoad()
    {
        try
        {
            // Load the students in each of the instructor's classes' info.
            pst = conn.prepareStatement("select stuID, prefix, fName, mName, lName, "
                                     + "suffix, uniEmail from student s, course c, "
                                     + "course_enrollment_list cel where name = ? "
                                     + "and (c.crn = cel.crn and s.stuID = cel.stuID)");
            pst.setString(1, course_combo_box.getSelectedItem().toString());
            rs = pst.executeQuery();
            
            // Set the number of the info table's rows to 0.
            ResultSetMetaData rsd = rs.getMetaData(); // To get the number of columns from the query
            dtm = (DefaultTableModel)student_info_table.getModel();
            dtm.setRowCount(0);
            
            // Load each student's info into the table.
            while (rs.next())
            {
                Vector vector = new Vector();
                
                for (int index = 1; index <= rsd.getColumnCount(); index++)
                {
                    vector.add(rs.getString("stuID"));
                    vector.add(rs.getString("prefix"));
                    vector.add(rs.getString("fName"));
                    vector.add(rs.getString("mName"));
                    vector.add(rs.getString("lName"));
                    vector.add(rs.getString("suffix"));
                    vector.add(rs.getString("uniEmail"));
                }
                
                dtm.addRow(vector); // Adds a student's info as one of the table's rows
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(modifyStudentInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_info_scroll_pane2 = new javax.swing.JScrollPane();
        student_info_table = new javax.swing.JTable();
        course_label = new javax.swing.JLabel();
        course_combo_box = new javax.swing.JComboBox<>();
        viewStudents_MenuBar = new javax.swing.JMenuBar();
        backButton = new javax.swing.JMenu();
        logoutButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        student_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Prefix", "fName", "mName", "lName", "Suffix", "uniEmail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_info_scroll_pane2.setViewportView(student_info_table);

        course_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        course_label.setText("Course:");

        course_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        course_combo_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                course_combo_boxMouseClicked(evt);
            }
        });

        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        viewStudents_MenuBar.add(backButton);

        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        viewStudents_MenuBar.add(logoutButton);

        setJMenuBar(viewStudents_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(course_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(student_info_scroll_pane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(student_info_scroll_pane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course_label)
                            .addComponent(course_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // Display staffHome.java.
        this.hide();
        new staffHome(id).setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // Display Login.java.
        this.hide();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void course_combo_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_course_combo_boxMouseClicked
        try
        {
            // Load the name of each course that the instructor is teaching.
            pst = conn.prepareStatement("select name from course, faculty where "
                                     + "(instructor_prefix = prefix) and "
                                     + "(instructor_fName = fName) and "
                                     + "(instructor_mName = mName) and "
                                     + "(instructor_lName = lName) and "
                                     + "(instructor_suffix = suffix) and "
                                     + "staffNo = ?");
            pst.setString(1, id);
            rs = pst.executeQuery();

            // Load all the courses' names into the combo box.
            String name; // The name of the course
            while (rs.next())
            {
                name = rs.getString("name");
                course_combo_box.addItem(name);
            }
            
            // Load the info of the students who're in the course into the table.
            studentLoad();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(viewStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_course_combo_boxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu backButton;
    private javax.swing.JComboBox<String> course_combo_box;
    private javax.swing.JLabel course_label;
    private javax.swing.JMenu logoutButton;
    private javax.swing.JScrollPane student_info_scroll_pane2;
    private javax.swing.JTable student_info_table;
    private javax.swing.JMenuBar viewStudents_MenuBar;
    // End of variables declaration//GEN-END:variables
}
